### ISSUE TITLE
FYI: two unimportant test failures on AArch64

### ISSUE THREAD

**Issue by rhenwood-arm** [aclements/go-gg#15]
Hi, It looks like this library is inactive currently, so this is an FYI issue:

After running the test suite on AArch64 I observed two failures:

```
=== RUN   TestBlank
--- PASS: TestBlank (0.00s)
=== RUN   TestGrid
--- PASS: TestGrid (0.00s)
=== RUN   TestLines
--- PASS: TestLines (0.00s)
=== RUN   TestCircles
--- PASS: TestCircles (0.00s)
=== RUN   TestQuadratic
--- FAIL: TestQuadratic (0.02s)
    context_test.go:26: expected hash: 56b842d814aee94b52495addae764a77
!= actual hash: 8bc90640363d48e4ed2b9741a3a52ffa
=== RUN   TestCubic
--- PASS: TestCubic (0.01s)
=== RUN   TestFill
--- PASS: TestFill (0.00s)
=== RUN   TestClip
--- PASS: TestClip (0.06s)
=== RUN   TestPushPop
--- FAIL: TestPushPop (0.00s)
    context_test.go:26: expected hash: 31e908ee1c2ea180da98fd5681a89d05
!= actual hash: 95ac5419a07df5b0916de3e8140ded54
=== RUN   TestDrawStringWrapped
--- PASS: TestDrawStringWrapped (0.00s)
=== RUN   TestDrawImage
--- PASS: TestDrawImage (0.02s)
=== RUN   TestSetPixel
--- PASS: TestSetPixel (0.00s)
=== RUN   TestDrawPoint
--- PASS: TestDrawPoint (0.00s)
=== RUN   TestLinearGradient
--- PASS: TestLinearGradient (0.00s)
=== RUN   TestRadialGradient
--- PASS: TestRadialGradient (0.00s)
=== RUN   TestDashes
--- PASS: TestDashes (0.01s)
FAIL
FAIL    _/tmp/gg-gg     0.155s
```

I have talked to a colleague about this. His analysis is:

"it is caused by the precision error generated by floating point operations(matrix transform). See: https://golang.org/ref/spec
An implementation may combine multiple floating-point operations into a single fused operation, possibly across statements, and produce a result that differs from the value obtained by executing and rounding the instructions individually. An explicit floating-point type conversion rounds to the precision of the target type, preventing fusion that would discard that rounding."

He has experience with graphics libraries and advised me that small differences in rendering are usually acceptable provided they cannot be observed by the human eye. This seems to be the case in this instance.

**Comment by ajstarks** [comment]
Also note that this package uses the integer version of SVGo.  The floating point version may be used by importing

```import "github.com/ajstarks/svgo/float```

**Comment by rhenwood-arm** [comment]
Oops. My colleague pointed out that I provided ambiguous package information. His analysis was based on the package: https://github.com/fogleman/gg 

There is an existing test failure report for that package: https://github.com/fogleman/gg/issues/79
